name: Fibonacci CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Clang
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 19

      - name: Add Clang to PATH
        run: echo "PATH=/usr/bin:$PATH" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake valgrind bat

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_CXX_COMPILER=clang++-19

      - name: Build all targets (parallel)
        run: cmake --build build --parallel

      - name: Run valgrind with callgrind
        run: |
          for algo in binet dp fast_doubling generator iterative_I matrix iterative_II recursive; do
            batcat --style full --force-colorization ./examples/fibonacci/fibonacci_$algo.cpp
            valgrind --tool=callgrind --callgrind-out-file=callgrind_out_$algo.log ./build/examples/fibonacci/main_$algo 40
            callgrind_annotate --inclusive=no callgrind_out_$algo.log
          done

      - name: Run main_all with valgrind
        run: |
          valgrind --tool=callgrind --callgrind-out-file=callgrind_out.log --dump-instr=yes --simulate-hwpref=yes --collect-jumps=yes --branch-sim=yes --cache-sim=yes --cacheuse=yes ./build/examples/fibonacci/main_all
          callgrind_annotate --inclusive=no callgrind_out.log

      - name: Run main_all with valgrind (each algorithm separate)
        run: |
          for algo in binet dp fast_doubling generator iterative_I matrix iterative_II recursive; do
            batcat --style full --force-colorization ./examples/fibonacci/fibonacci_$algo.cpp
            valgrind --tool=callgrind --callgrind-out-file=callgrind_out_$algo.log --dump-instr=yes --simulate-hwpref=yes --collect-jumps=yes --branch-sim=yes --cache-sim=yes --cacheuse=yes ./build/examples/fibonacci/main_all
            callgrind_annotate --inclusive=no callgrind_out_$algo.log
          done